# SPDX-FileCopyrightText: Copyright 2024 Siemens AG
#
# SPDX-License-Identifier: MPL-2.0

variables:
  http_proxy: $CODE_PROXY
  https_proxy: $CODE_PROXY
  no_proxy: $CODE_NO_PROXY

stages:
  - check
  - build

reuse-and-codestyle:
  stage: check
  image: python:latest
  variables:
    GIT_DEPTH: "0"
  before_script:
    - apt-get update && apt-get install -y python3-gi flake8 pylint python3-pydbus
    - pip3 install --break-system-packages fsfe-reuse
    - git clean -f -d
  script:
    - reuse lint
    - flake8
    - pylint sso-mib.py

build-xpi:
  stage: build
  image: debian:bookworm-slim
  before_script:
    - apt-get update && apt-get install -y make git zip
  script:
    - make package
  artifacts:
    paths:
      - build/firefox/sso-mib*.xpi
