# SPDX-FileCopyrightText: Copyright 2024 Siemens AG
#
# SPDX-License-Identifier: MPL-2.0

variables:
  http_proxy: $CODE_PROXY
  https_proxy: $CODE_PROXY
  no_proxy: $CODE_NO_PROXY

stages:
  - check
  - build

reuse-and-codestyle:
  stage: check
  image: python:latest
  variables:
    GIT_DEPTH: "0"
  before_script:
    - python3 -m venv ../venv
    - . ../venv/bin/activate
    - pip3 install fsfe-reuse flake8
    - git clean -f -d
  script:
    - reuse lint
    - flake8

build-xpi:
  stage: build
  image: debian:bookworm-slim
  before_script:
    - apt-get update && apt-get install -y make git zip
  script:
    - make package
  artifacts:
    paths:
      - "sso-mib*.xpi"
