variables:
  http_proxy: $CODE_PROXY
  https_proxy: $CODE_PROXY
  no_proxy: $CODE_NO_PROXY

stages:
  - build

build-xpi:
  stage: build
  image: debian:bookworm-slim
  before_script:
    - apt-get update && apt-get install -y make git zip
  script:
    - make package
  artifacts:
    paths:
      - "sso-mib*.xpi"
